### PR TITLE
refactor(workflow): pr title validation update

### PR DESCRIPTION
**Pull request by ulfgebhardt**
## 🍰 Pullrequest

pr title validation update requested by a comment on the implementing PR https://github.com/cypht-org/cypht/pull/1379#issuecomment-2500269681

Adds 4 new types for pr scopes observed in cypht:
- frontend
- backend
- frontend/backend
- backend/frontend

Furhtermore a comprehensive guide was added to the pull request template to make it easier for people to fullfil this requirement.

### Example

image

### Issues

- requirements https://github.com/cypht-org/cypht/pull/1379#issuecomment-2500269681
- relates https://github.com/cypht-org/cypht/pull/1379
- relates https://github.com/ulfgebhardt/issue-templates/commit/56dc4aa7847cae10de1bf1b3d0f301a519882dab

### Todo

- [ ] Verify that no scope, observed lately, is missing

### CODE REVIEW

**Comment by mercihabam** [comment]
@ulfgebhardt, thank you for your response to my comment!

Here is my feedback:

- I suggest excluding the scopes "cypht" and "other" as they do not indicate that any specific part of the project has been affected.
- `docs` sounds more appropriate as a scope compared to `docu`.
- In the proposed update, we have both `frontend/backend` and `backend/frontend`. I recommend keeping only one variation for consistency.
- These additional scopes could be useful: `modules/output`, `modules/handler`, `tests/unit`, and `tests/e2e`.

**Comment by ulfgebhardt** [comment]
> @ulfgebhardt, thank you for your response to my comment!
> 
> Here is my feedback:
> 
> * I suggest excluding the scopes "cypht" and "other" as they do not indicate that any specific part of the project has been affected.
> * `docs` sounds more appropriate as a scope compared to `docu`.
> * In the proposed update, we have both `frontend/backend` and `backend/frontend`. I recommend keeping only one variation for consistency.
> * These additional scopes could be useful: `modules/output`, `modules/handler`, `tests/unit`, and `tests/e2e`.

I implemented your suggestions, except the removal of `other`. I can remove it if you want, but its always useful to give people an option to escape things in case you did not think about everything.

Furthermore I suggest to simplify your suggestions further:
- instead of `modules/output` and `modules/handler` i suggest to just use `modules` - or better  sigular `module`
- instead of `tests/unit` `tests/e2e` I suggest to use just `unit` and `e2e` since your title would be something like `test(unit): my test`.

Let me know what you think

**Comment by mercihabam** [comment]
That works for me, please go ahead!

**Comment by mercihabam** [comment]
Looks good!

**Pull request merged**
