### PR TITLE
When reading literal_data from mail body from IMAP, use byte count instead of string-length count.

### LINKED ISSUE #1119: FastCGI timeout (Not docker related)
## 🐛 Bugreport

I am running cypht using docker compose. Building the docker image from source locally. 
Previous version ran without the issue described here (master branch ca. month ago). After updating to the most recent master branch, the issue began.

Cypht comes up as regular, and is usable (there are some issues regarding the Everything folder not displaying all accounts, but that was unchanged between versions).
After some usage, usually just a few minutes, cypth becomes unreachable, with the browser displaying just: "504 Gateway Time-out
nginx/1.26.1". Sometimes, browser says "404 page not found".

In the docker logs, I get the following:
```
<< fastCGI error is repeated a lot >>
cypht-1  | 172.22.0.2 - - [15/Jul/2024:11:17:56 +0000] "POST / HTTP/1.1" 504 569 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36"
cypht-1  | 127.0.0.1 -  15/Jul/2024:11:18:10 +0000 "POST /index.php" 200
cypht-1  | 172.22.0.2 - - [15/Jul/2024:11:18:10 +0000] "POST / HTTP/1.1" 200 78 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36"
cypht-1  | 127.0.0.1 -  15/Jul/2024:11:18:14 +0000 "GET /index.php" 200
cypht-1  | 127.0.0.1 - - [15/Jul/2024:11:18:14 +0000] "GET / HTTP/1.1" 200 510848 "-" "curl/8.7.1"
cypht-1  | 127.0.0.1 -  15/Jul/2024:11:18:26 +0000 "POST /index.php" 200
cypht-1  | 172.22.0.2 - - [15/Jul/2024:11:18:26 +0000] "POST / HTTP/1.1" 200 21209 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36"
cypht-1  | 127.0.0.1 -  15/Jul/2024:11:18:26 +0000 "POST /index.php" 200
cypht-1  | 172.22.0.2 - - [15/Jul/2024:11:18:27 +0000] "POST / HTTP/1.1" 200 21209 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36"
cypht-1  | 127.0.0.1 -  15/Jul/2024:11:18:27 +0000 "POST /index.php" 200
cypht-1  | 172.22.0.2 - - [15/Jul/2024:11:18:27 +0000] "POST / HTTP/1.1" 200 276 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36"
cypht-1  | 127.0.0.1 -  15/Jul/2024:11:18:27 +0000 "POST /index.php" 200
cypht-1  | 172.22.0.2 - - [15/Jul/2024:11:18:28 +0000] "POST / HTTP/1.1" 200 20364 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36"
cypht-1  | 127.0.0.1 -  15/Jul/2024:11:18:28 +0000 "POST /index.php" 200
cypht-1  | 172.22.0.2 - - [15/Jul/2024:11:18:28 +0000] "POST / HTTP/1.1" 200 285 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36"
cypht-1  | 127.0.0.1 -  15/Jul/2024:11:18:44 +0000 "GET /index.php" 200
cypht-1  | 127.0.0.1 - - [15/Jul/2024:11:18:44 +0000] "GET / HTTP/1.1" 200 510848 "-" "curl/8.7.1"
cypht-1  | 127.0.0.1 -  15/Jul/2024:11:19:10 +0000 "POST /index.php" 200
cypht-1  | 172.22.0.2 - - [15/Jul/2024:11:19:10 +0000] "POST / HTTP/1.1" 200 78 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36"
cypht-1  | 127.0.0.1 -  15/Jul/2024:11:19:14 +0000 "GET /index.php" 200
cypht-1  | 127.0.0.1 - - [15/Jul/2024:11:19:14 +0000] "GET / HTTP/1.1" 200 510840 "-" "curl/8.7.1"
cypht-1  | 172.22.0.2 - - [15/Jul/2024:11:19:20 +0000] "POST / HTTP/1.1" 504 569 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36"
cypht-1  | 2024/07/15 11:19:20 [error] 26#26: *23322 upstream timed out (110: Operation timed out) while reading response header from upstream, client: 172.22.0.2, server: localhost, request: "POST / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "mail.example.com <<I replaced the actual host of my mail server here>>"
cypht-1  | 127.0.0.1 -  15/Jul/2024:11:19:45 +0000 "GET /index.php" 200
cypht-1  | 127.0.0.1 - - [15/Jul/2024:11:19:45 +0000] "GET / HTTP/1.1" 200 510848 "-" "curl/8.7.1"
cypht-1  | NOTICE: PHP message: PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /usr/local/share/cypht/modules/imap/hm-imap-base.php on line 80
cypht-1  | NOTICE: PHP message: PHP Stack trace:
cypht-1  | NOTICE: PHP message: PHP   1. {main}() /usr/local/share/cypht/site/index.php:0
cypht-1  | NOTICE: PHP message: PHP   2. Hm_Dispatch->__construct($config = class Hm_Site_Config_File { protected $so


```
After the "PHP Fatal error" is displayed, cypht becomes reachable again. 
Once I'm in again, I notice, that the email I was reading once it became unresponsive (mail from a gmail account) is still marked as unread in the mail listing. Otherwise, marking unread mails as read once I have opened them works as expected.

### Version & Environment
git commit : 5e88e1463494b59ed3aca65a15402c2537e77afa
OS : docker image, running on x64 host which is running debian.

### PR DESCRIPTION
**Pull request by indridieinarsson**
## Pullrequest
This is a first attempt to fix issue #1119. 
I'm not very proficient in php, and not knowledgeable about imap, so for the love of all that is good and holy, review and test this properly.

Take a look at this chunk from hm-imap-base.php:
> elseif ($line[$i] == '{') {
>                 $end = mb_strpos($line, '}');
>                 if ($end !== false) {
>                     $literal_size  = mb_substr($line, ($i + 1), ($end - $i - 1));
>                 }
>                 $lit_result = $this->read_literal($literal_size, $max, $current_size, $line_length);
>                 $chunk = $lit_result[0];
> 

If I understand this writing correctly: https://www.rfc-editor.org/rfc/rfc3501#section-4.3, the number in curly braces that is being read into $literal_size, is the number of bytes in the email body, which is then sent over the wire right away.
Therefore, all string-size calculations in `read_literal()` should use the `strsize` rather than `mb_strsize` command. My theory is that the issue #1119 is caused by this: the number of bytes read are underestimated since `mb_strsize` is smaller than `strsize` for real multibyte strings. We then end up trying to read strings from the server after the server has sent the entire message, causing the code to hang. 

### Issues

- Might possibly fix #1119 

### Checklist
This touches the code that reads the email body, pretty central for an email client. This PR will change behaviour in cases when the body of the message contains multibyte characters (ÞþæÆöÖðÐáÁóÓ etc.).

### CODE REVIEW

**Review by kambereBr — APPROVED** [review]
Looks good! Fix the pipelines, and we’ll merge. We'll keep an eye on the changes. Thanks!

**Comment by indridieinarsson** [comment]
@kambereBr  : I can't really figure out how to get the Selenium test to pass. Can't see that my code should have change what the test is checking. Is the test somehow broken? Or has a previous commit inadvertently broken it?

**Comment by indridieinarsson** [comment]
I installed the version in my feature-branch, with bunch of emails and 3 accounts. With the exception of an already reported issue, everything works as expected. In particular, the Selenium test that is failing is not reproducible in the browser.

**Comment by indridieinarsson** [comment]
Ok, I did some searching around. Seems the test was failing due to a race condition.
* We find an element and check its text.
*  Then we refresh the message list, which also reloads the page, and in that process, the element we were looking for is nuked and rebuild.
*  Then we go on to the next line to find the element again, but the reference is still pointing to the old element at this point, since the refresh is not yet finished, so we still get a reference to the old element. 
* the old element is stale, and we get an error
I added some code that waits for the element to be available and not stale. If the element is not available after a timeout of 10s, it should throw an error.

Someone might want to re-review this PR, as I fiddled with the tests.

**Comment by marclaporte** [comment]
> This touches the code that reads the email body, pretty central for an email client. This PR will change behaviour in cases when the body of the message contains multibyte characters (ÞþæÆöÖðÐáÁóÓ etc.).

Well, I think it reverts some of the recent changes so it restores code to what is was for a long time.

**Comment by marclaporte** [comment]
Here is the change: https://github.com/cypht-org/cypht/pull/1051

Could some of the other changes have unintendended negative consequences?

**Comment by kambereBr** [comment]
> Here is the change: #1051
> 
> Could some of the other changes have unintendended negative consequences?

Probably yes, but it's hard to say for sure. We'll only know when we encounter issues in specific use cases.

**Comment by kroky** [comment]
@indridieinarsson thanks for the PR but since we have more problems than the mentioned issue with literal string lengths, I combined your code with other fixes and some unit tests to catch this issue in the future here: https://github.com/cypht-org/cypht/pull/1230
Note for the discussion about using 8-bit string functions vs multibyte ones: we prefer and should use the multibyte functions everywhere we deal with strings in Cypht. The only exception seems to be here in imap module where literal lengths is specified in bytes rather than characters. It is actually somewhat strange as the RFC mentions only 7-bit encoding or 8-bit ones but maybe some mail servers still use unencoded multibytes in those literals. Thus, we make sure that read_literal works on bytes and doesn't check individual bytes for valid character values.
The other problem is unfinished changes from the multibyte conversion where accessing a string via array offset is not actually working for multibyte strings - we should use mb_substr in those cases.

**Pull request closed without merging**
