### PR TITLE
Added bootstrap to carddav and ldap contacts modules

### PR DESCRIPTION
**Pull request by josaphatim**
This MR adds bootstrap to carddav contacts and ldap contacts modules

### CODE REVIEW

**Comment by alvinBM** [comment]
hello @josaphatim 
Thank you for noticing these modules which were forgotten during the bootstrap migration. 
For the ldap_contacts module, I suggest you use the [Floating label](https://getbootstrap.com/docs/5.0/forms/floating-labels/)  on the form fields as this form is very long, to always have the name of the field visible when it is edited or when it is filled. So you could also get rid of the `.screen_reader` class on the `label` tags

**Comment by josaphatim** [comment]
> hello @josaphatim Thank you for noticing these modules which were forgotten during the bootstrap migration. For the ldap_contacts module, I suggest you use the [Floating label](https://getbootstrap.com/docs/5.0/forms/floating-labels/) on the form fields as this form is very long, to always have the name of the field visible when it is edited or when it is filled. So you could also get rid of the `.screen_reader` class on the `label` tags

Thanks @alvinBM copy that !

**Comment by josaphatim** [comment]
@alvinBM now ready.

**Comment by alvinBM** [comment]
> @alvinBM now ready.

Thanks @josaphatim

**Pull request merged**
