### PR TITLE
Backporting menus (junk, trash and drafts) to 1.4.x

### PR DESCRIPTION
**Pull request by Yannick243**
Backporting menus (all junk, all trash and all drafts) to 1.4.x

Cherry picked from: [https://github.com/cypht-org/cypht/commit/b622c291c8d82f01936f25145339e09de8a60988](https://github.com/cypht-org/cypht/commit/b622c291c8d82f01936f25145339e09de8a60988)

### CODE REVIEW

**Comment by marclaporte** [comment]
Already some good stuff for upcoming 1.4.2 :-)

**Comment by josaphatim** [comment]
@Yannick243 there is a failing test. Also please resolve conflicts.

**Comment by Yannick243** [comment]
@josaphatim conflicts have been resolved, all failling tests have been fixed here [https://github.com/cypht-org/cypht/pull/827](https://github.com/cypht-org/cypht/pull/827)

**Comment by josaphatim** [comment]
@Yannick243 below 

This branch cannot be rebased due to conflicts

**Pull request merged**
