### PR TITLE
change the order of options for account creation

### PR DESCRIPTION
**Pull request by David-Muhasa**
### Issues

- [X] None

### Checklist

- [X] None

### How2Test

- [X] None

### Todo

- [X] None

### CODE REVIEW

**Comment by josaphatim** [comment]
@David-Muhasa If think this changes are wrong
They make modules tied. If you try to disable module wordpress you will notice that other sections in servers page will disappear as well

If think the best way to do this is:
**In modules/feeds/setup.php**
replace server_content_start by server_content_end and change the marker as well from after to before

**In modules/nux/setup.php**
Replace server_config_stepper_accordion_end_part by server_content_start

In this manner the order for sections will be
```
Add an E-mail Account
IMAP - JMAP - SMTP Servers
Feeds
NASA APIs
WordPress.com Connect
Github Connect
```

Please also handle the case when smtp, imap and jmap modules are not disabled
Hm_Output_server_config_stepper_end_part must be visible if at least one of those modules is enabled

**Comment by David-Muhasa** [comment]
@josaphatim  I try to put your orientation into practice and then I will come back to you

**Comment by David-Muhasa** [comment]
hello @josaphatim

**Comment by marclaporte** [comment]
@David-Muhasa since you are new to the project, you should not merge your own PRs, but instead let @josaphatim or another experienced dev do so.

**Comment by David-Muhasa** [comment]
It was by mistake. I directly called Mr Josaphat

**Pull request merged**
