### PR TITLE
Define constant for theme path

### PR DESCRIPTION
**Pull request by Shadow243**
Related issue https://github.com/cypht-org/cypht/issues/1147

I tried to do it through config_gen file much like site.css but i had some issues, I the tries using theme constant for tiki standalone and the same one in Tiki Cypht Integration.

Tiki Cypht PR: https://gitlab.com/tikiwiki/tiki/-/merge_requests/5611

### CODE REVIEW

**Comment by Shadow243** [comment]
Three Selenium tests are broken now:

- `hide_folders`
- `show_folders`

in `folder_list.py`. I'll need time to identify where this is coming from and will correct them in another PR.

**Comment by kroky** [comment]
Alright, the way you do it makes sense to me. Merged it!

**Comment by marclaporte** [comment]
@Shadow243 This should be backported to branch 2.x, and the corresponding Tiki commit to Tiki 27.x

**Comment by Shadow243** [comment]
> @Shadow243 This should be backported to branch 2.x, and the corresponding Tiki commit to Tiki 27.x

Copy that.

**Comment by Shadow243** [comment]
> @Shadow243 This should be backported to branch 2.x, and the corresponding Tiki commit to Tiki 27.x

Done at https://github.com/cypht-org/cypht/pull/1200

**Pull request merged**
