### PR TITLE
feat(other): update issue templates

### PR DESCRIPTION
**Pull request by ulfgebhardt**
## Pullrequest

Update issue templates

image

### Motivation
Since I am invested in testing cypht lately, i figured the issue templates are now 6 years old and have evolved on my end a bit.
So here is an update.

### What has changed?

- Templates are more simple so developers are actually tempted not to just replace the whole contents but fill out the data (see pullrequest template especially)
- The title of a new issue will be preset. This results in well organized issue lists with visual cues what type of issue it is with no effort for the issue creator
- There is new types of issues: epic, devops, refactor, release
- The suggestion type is gone
- There is a new workflow which checks if a PR title is well formed. This needs some getting used to, but results in a nice changelog based on PR titles.

You can explore how things would look like here: https://github.com/ulfgebhardt/issue-templates

Example of a well formed changelog generated by https://github.com/CookPete/auto-changelog
image

### Issues

- [X] None

### Todo

- [x] Decided if all types should be part of the repo - is epic a thing here? Is devops needed?
- [ ] Do you want the PR title workflow?
- [x] Create all labels for the types decided for - see https://github.com/ulfgebhardt/issue-templates?tab=readme-ov-file#labels

### CODE REVIEW

**Comment by marclaporte** [comment]
"is epic a thing here?"

Let's look at current list at https://github.com/cypht-org/cypht/issues and see if some would qualify. Would these qualify?

- https://github.com/cypht-org/cypht/issues/1308
- https://github.com/cypht-org/cypht/issues/1354
- https://github.com/cypht-org/cypht/issues/1256
- https://github.com/cypht-org/cypht/issues/1146
- https://github.com/cypht-org/cypht/issues/1136
- https://github.com/cypht-org/cypht/issues/1048

**Comment by marclaporte** [comment]
"Is devops needed?"

Maybe for tasks related to Docker?

**Comment by ulfgebhardt** [comment]
> "is epic a thing here?"
> 
> Let's look at current list at https://github.com/cypht-org/cypht/issues and see if some would qualify. Would these qualify?
> 
> * [Improve the UX of the Sieve filter editor #1308](https://github.com/cypht-org/cypht/issues/1308)
> * [There is a trillion themes... #1354](https://github.com/cypht-org/cypht/issues/1354)
> * [[Proposal for Cypht 3.0] Enhance Cypht UI with Customized Bootstrap 5 and jQuery 3.7.1 #1256](https://github.com/cypht-org/cypht/issues/1256)
> * [What can we learn and implement from the Docker strategy of other webmail project? #1146](https://github.com/cypht-org/cypht/issues/1146)
> * [The WYSIWYG editor used by Cypht "has been archived by the owner on Jan 9, 2024. It is now read-only." #1136](https://github.com/cypht-org/cypht/issues/1136)
> * [Rethinking Hm_Functions #1048](https://github.com/cypht-org/cypht/issues/1048)

Epic is normally a greater goal, which then is comprised of several features. An example would be: "Provide an native android App" or "Implement AI driven E-Mail writing".

Of the list you provide
- #1308 does not quality since its an improvement
- #1354 is a bugreport, but refactoring themes could be an greater goal
- #1256 seems appropriate, but could also be a Release type.
- #1146 is more research and would qualify as Question type.
- #1048 could be an epic, but also a question

In general I use Epic and Release types for planning purposes - normally users don't create those issue, but Project leads, eg. to define the scope of an upcoming release. This utilizes issues to track progress and have strategic notes/goals available for everyone. I am unsure this project qualifies for this kind of approach.

---

> "Is devops needed?"
> 
> Maybe for tasks like this: https://github.com/cypht-org/cypht/issues/1175

I think the linked issue would qualify for this - I tend to use Devops for everything related to the souroundings of the project, like deployments, backups etc. I am not 100% sure this projects qualifies for this, since except the website there is no deployments actively maintained by the project itself.

---

Please decide what you need and I will adjust the PR accordingly. If you need more info, I can try to help.

Another approach could be to provide all types and see how people use them - but that's something the project maintainers need to do.

Another thing: The PR title validation contains a regex, which enforces PRs to start with a lower case character after its scope and type definitions(see https://github.com/cypht-org/cypht/pull/1379/files#diff-e788ba1b09f963893d3d6774df945f463f70052aa1fe6d7080bbaf38568a8646R46) - this tends to confuse people and is there for the sake of visual pleasure in a changelog.
> Valid: `type(scope): my PR title`
> Invalid: `type8scope): My PR title`

**Comment by marclaporte** [comment]
> Epic is normally a greater goal, which then is comprised of several features.

I like this concept, and since we have examples, I think we should keep.

**Comment by marclaporte** [comment]
@ulfgebhardt 

Recently, I added "technical debt" on another bug tracker:
https://tiki.org/blogpost984-Added-a-category-for-technical-debt-on-dev-tiki-org

How would deal with a task of this type? For example: https://github.com/cypht-org/cypht/issues/1136

**Comment by marclaporte** [comment]
> Create all labels for the types decided for

Indeed, labels should aligned. Can you please review current labels and recommend which ones should be added / removed / merged?

Thanks!

**Comment by ulfgebhardt** [comment]
> @ulfgebhardt
> 
> Recently, I added "technical debt" on another bug tracker: https://tiki.org/blogpost984-Added-a-category-for-technical-debt-on-dev-tiki-org
> 
> How would deal with a task of this type? For example: #1136

This I would qualify as Refactor, since it improves/changes existing code without changing behaviour.

---

> > Create all labels for the types decided for
> 
> Indeed, labels should aligned. Can you please review current labels and recommend which ones should be added / removed / merged?
> 
> Thanks!

The following labels are used by the templates, ~~strikethrough~~ are already present in the Repo:
- ~~bug~~
- devops
- epic
- feature
- ~~question~~
- refactor
- release

Hence, when all templates are merged `devops`, `epic`, `feature`, `refactor` and `release` should be created to automatically assign this label when an issue is created. If the label is not present no label is automatically assigned.

---

> > * Do you want the PR title workflow?
> 
> I am undecided. Let's see what others say.

Since you seem not to require test to pass (selenium is failing, but my branch can be merged) this decision can also be postponed and checked if things work as you expect - then the workflow can be made a requirement

--- 

> > Since I am invested in testing cypht lately
> 
> @ulfgebhardt: This is highly appreciated. In the last year, we have seen a record number of contributors: https://openhub.net/p/cypht/contributors/summary
> 
> Lots of new features Lots of devs that are new to the code base (and don't have a lot of experience using Cypht)
> 
> So I feel 1.4.x is more stable than 2.x (and even more so master)
> 
> Over the next few months, the focus will increasingly be on fixing bugs. So we really need testers. So your help is deeply appreciated.

To increase stability you need more tests and you **MUST** make them reliable - flaky tests as I see them in this project are not helping - they undermine the developers trust in the tests. It is very important, that a developer knows he did something wrong if he fails a test - he must be able to rely on that. It will make it easier for developers & for maintainers to judge if code is working correctly. Furthermore beginners are able to get automatic feedback from the development environment about their work without bothering people about it.

I might be able to assist with that if I find the time.

Test milestones would be:
- remove flakyness
- require coverage goal
- enforce code style via linting
- static analysis via linting
- > 95% test coverage
- fullstack tests

**Comment by marclaporte** [comment]
> This I would qualify as Refactor, since it improves/changes existing code without changing behaviour.

works for me

**Comment by marclaporte** [comment]
> The following labels are used by the templates

I added to https://github.com/cypht-org/cypht/labels

**Comment by marclaporte** [comment]
> this decision can also be postponed and checked if things work as you expect

works for me

**Comment by ulfgebhardt** [comment]
> > this decision can also be postponed and checked if things work as you expect
> 
> works for me

Feel free to merge then unless you want more feedback.

**Comment by marclaporte** [comment]
> I might be able to assist with that if I find the time.

This is fantastic! With guidance, our several keen and young developers will learn and improve tests.

**Comment by marclaporte** [comment]
> Feel free to merge

Was going to merge but the selenium tests are failing so I just relaunched them.

**Comment by marclaporte** [comment]
Still failing but merged anyways.

**Pull request merged**
