### PR TITLE
Correct imap buttons on servers page & trigger change sieve_mode_tls checkbox on edit server

### PR DESCRIPTION
**Pull request by Shadow243**
Follow up to https://github.com/cypht-org/cypht/pull/1199 & https://github.com/cypht-org/cypht/pull/1266

### CODE REVIEW

**Comment by jacob-js** [comment]
@Shadow243 I am skeptical as to why the pipeline succeeded here while containing mistakes to the test, showing up in follow-up pull requests. Does the pipeline run on cached content?

**Comment by Shadow243** [comment]
> @Shadow243 I am skeptical as to why the pipeline succeeded here while containing mistakes to the test, showing up in follow-up pull requests. Does the pipeline run on cached content?

It's weird, this test doesn't work sometimes, I even opened another PR https://github.com/cypht-org/cypht/pull/1290 to fix this, with the same fix you applied my test didn't pass. let's see if it won't break anymore.

**Comment by jacob-js** [comment]
> > @Shadow243 I am skeptical as to why the pipeline succeeded here while containing mistakes to the test, showing up in follow-up pull requests. Does the pipeline run on cached content?
> 
> It's weird, this test doesn't work sometimes, I even opened another PR #1290 to fix this, with the same fix you applied my test didn't pass. let's see if it won't break anymore.

As for the test, it is stable. Reintroducing the line `self.wait_for_navigation_to_complete()` worked for you as well, but you encountered a separate test failure that was fixed with this [change](https://github.com/cypht-org/cypht/pull/1288/commits/afbaff02a1b581b810234ba1e275f05faddaeaf5#diff-015513616f5a3e387c6d1e06e82a29d9be33debc8de739fcf998719ab2d62280R87).

It is still confusing that the pipeline sometimes runs against old content (seemingly from the master branch) rather than the actual branch state.

**Comment by Shadow243** [comment]
> > > @Shadow243 I am skeptical as to why the pipeline succeeded here while containing mistakes to the test, showing up in follow-up pull requests. Does the pipeline run on cached content?
> > 
> > 
> > It's weird, this test doesn't work sometimes, I even opened another PR #1290 to fix this, with the same fix you applied my test didn't pass. let's see if it won't break anymore.
> 
> As for the test, it is stable. Reintroducing the line `self.wait_for_navigation_to_complete()` worked for you as well, but you encountered a separate test failure that was fixed with this [change](https://github.com/cypht-org/cypht/pull/1288/commits/afbaff02a1b581b810234ba1e275f05faddaeaf5#diff-015513616f5a3e387c6d1e06e82a29d9be33debc8de739fcf998719ab2d62280R87).
> 
> It is still confusing that the pipeline sometimes runs against old content (seemingly from the master branch) rather than the actual branch state.

Super, i then close #1290.

**Pull request merged**
