### PR TITLE
Removing CRAM-MD5 mechanism

### PR DESCRIPTION
**Pull request by Danelif**
This PR aims to remove CRAM-MD5 mechanism from cypht

Suggested here: https://github.com/cypht-org/cypht/issues/355

### CODE REVIEW

**Comment by marclaporte** [comment]
@Neustradamus please advise.

**Comment by Neustradamus** [comment]
@Danelif: I think, you must to look SCRAM before merging:
- https://github.com/cypht-org/cypht/issues/354#issuecomment-2147276527

Several PHP projects support already several SCRAM (badly not -PLUS variants).

Note: LOGIN is not secure too.

**Comment by Danelif** [comment]
Should i provide an other PR or try to implement SCRAM in the Same PR removing CRAM-MD5 ?? @Neustradamus

**Comment by Neustradamus** [comment]
@Danelif: Another one :)

**Comment by marclaporte** [comment]
ok, but this must not be merged in until stronger SCRAM is available. Many people run Cypht from master, and we release versions from master.

**Comment by marclaporte** [comment]
@Danelif Please resolve conflicts.

**Comment by Danelif** [comment]
This PR was forbidden by @kroky so it has to be closed.

**Comment by marclaporte** [comment]
Right. So weaker mechanisms are still better than plain password.

**Pull request closed without merging**
