### PR TITLE
improve JMAP compatibilities with stalwart

### PR DESCRIPTION
**Pull request by Shadow243**
This Pull Request follows a proposal that had been made: [https://github.com/cypht-org/cypht/pull/648](https://github.com/cypht-org/cypht/pull/648) adding support for JMAP in Cypht.

### CODE REVIEW

**Comment by Shadow243** [comment]
Currently, we have left it as draft pending this fix [https://github.com/cypht-org/cypht/pull/902](https://github.com/cypht-org/cypht/pull/902) which will fix email sending as it is not working for now. We have been not able to test send mail

**Comment by landryb** [comment]
fwiw it seems [4bc4cea](https://github.com/cypht-org/cypht/pull/909/commits/4bc4cea2d7f020f74419289944959458a3d11313) reverts the previous commits in hm-jmap

**Comment by Shadow243** [comment]
> fwiw it seems [4bc4cea](https://github.com/cypht-org/cypht/pull/909/commits/4bc4cea2d7f020f74419289944959458a3d11313) reverts the previous commits in hm-jmap

We started with your commits then added another, we now have your 4 commits plus 1(5 commits)

**Comment by landryb** [comment]
> > fwiw it seems [4bc4cea](https://github.com/cypht-org/cypht/pull/909/commits/4bc4cea2d7f020f74419289944959458a3d11313) reverts the previous commits in hm-jmap
> 
> We started with your commits then added another, we now have your 4 commits plus 1(5 commits)

yes, but unless i'm mistaken and dont understand the github UI anymore, if you look at the actual PR contents on https://github.com/cypht-org/cypht/pull/909/files there's only a oneliner change which comes from 4bc4cea, and all the other changes from the previous 4 commits are reverted in it...

**Comment by kroky** [comment]
@landryb is right - the original commits were reverted as part of another one - namely, this one: https://github.com/cypht-org/cypht/pull/909/commits/4bc4cea2d7f020f74419289944959458a3d11313

@Shadow243 can you please revert that and start with the original 4 commits and then introduce the changes you want? I think we should address the commenting of the isPrimary check - if that's not needed, just remove the code.

**Comment by Shadow243** [comment]
Changes separated here: https://github.com/cypht-org/cypht/pull/909/commits/e9cecf960c4fd180e873bbbea038a5a7e50b5b50

**Comment by landryb** [comment]
i havent been able to test more jmap since 1.5 year, so dont wait for me :) hopefully someday i'll be able to retest cypht against stalwart-jmap...

**Pull request merged**
