### PR TITLE
Added MDN/SDN to compose form

### PR DESCRIPTION
**Pull request by josaphatim**
Fixes https://github.com/jasonmunro/cypht/issues/687

Add MDN / SDN checkboxes to compose form.

### CODE REVIEW

**Comment by kroky** [comment]
This PR addresses the request part only (checkboxes on compose form) but Cypht is also a MUA that should handle the recipient part of the story as well (or should it?).
MTA can optionally respond with MDN or might leave that to MUA. See https://datatracker.ietf.org/doc/html/rfc8098#autoid-10 for format of the MDN that should be sent and also https://datatracker.ietf.org/doc/html/rfc8098#autoid-26 - we have a lot to implement in Cypht if we want to support the full timeline of events.
Is the PR only supposed to allow requesting these MDNs but not respond to them? I think @jasonmunro disagrees with integrating them in Cypht, at least with the recipient part of the story.

**Comment by josaphatim** [comment]
@kroky I made changes please check

**Comment by kroky** [comment]
OK, I think the code is good to be merged for the part that requests a MDN. It seems we didn't have an agreement to implement recipient part of the MDN (sending MDNs from cypht), so leaving that for later.
@josaphatim can you please resolve the conflicts and we can merge.

**Comment by josaphatim** [comment]
@kroky now read

**Pull request merged**
