### PR TITLE
Fixed Class ScramAuthenticator not found in modules/imap/hm-imap.php

### PR DESCRIPTION
**Pull request by josaphatim**
Fixes PHP Fatal error:  Uncaught Error: Class "ScramAuthenticator" not found in /path/to/cypht/modules/imap/hm-imap.php:174

This is breaking login page for now

### CODE REVIEW

**Comment by marclaporte** [comment]
@kroky @Danelif

**Comment by Danelif** [comment]
the scram.php file was in the wrong directory. I did not see the bug because of the browser caches. Thanks @josaphatim

**Comment by Neustradamus** [comment]
Linked to:
- https://github.com/cypht-org/cypht/pull/1072
- https://github.com/cypht-org/cypht/pull/1082
- https://github.com/cypht-org/cypht/pull/1083

**Comment by Neustradamus** [comment]
Linked to:
- https://github.com/scram-sasl/info/issues/1
- https://github.com/cypht-org/cypht/pull/1072
- https://github.com/cypht-org/cypht/pull/1082
- https://github.com/cypht-org/cypht/pull/1083

**Pull request merged**
