### PR TITLE
Replaced image icons by bootstrap icons

### PR DESCRIPTION
**Pull request by josaphatim**
This PR replaces image icons by bootstrap icons.

### CODE REVIEW

**Comment by kroky** [comment]
@josaphatim @Shadow243 and anybody working on the bootstrap upgrade - can you please run phpunit after making your changes and make sure the tests pass? There are quite some tests checking html output and the bootstrap upgrade breaks them.

**Comment by josaphatim** [comment]
> @josaphatim @Shadow243 and anybody working on the bootstrap upgrade - can you please run phpunit after making your changes and make sure the tests pass? There are quite some tests checking html output and the bootstrap upgrade breaks them.

@kroky Now on master there are a total of 19 tests failing. And others will definitely break when we merge. There are only 4 MR left regarding bootstrap I would suggest repairing all the tests once these 4 have been merged since there will be no more changes on the html side. I don't know if this suits you.

**Comment by kroky** [comment]
Alright, we can fix when all bootstrap merges are done. Btw, I have already fixed at least a dozen of bootstrap tests as part of the IDs-for-everything task but it seems we need to fix more.

**Comment by josaphatim** [comment]
> Alright, we can fix when all bootstrap merges are done. Btw, I have already fixed at least a dozen of bootstrap tests as part of the IDs-for-everything task but it seems we need to fix more.

Thanks @kroky I have already fixed remaining tests

**Pull request merged**
