### PR TITLE
Merge tag v2.2.0 into 2.x

### PR DESCRIPTION
**Pull request by Shadow243**
This PR is merging missing commits from tag 'v2.2.0' into 2.x

### CODE REVIEW

**Comment by Shadow243** [comment]
> There seems to be a few more that should also be in 2.x: [2.x...master](https://github.com/cypht-org/cypht/compare/2.x...master)

Maybe this one: https://github.com/cypht-org/cypht/commit/e70db0ee833f27d9e009dc2d0e381f35b8792b8b the rest came after the release. even this last one came after the Docker release.

**Comment by marclaporte** [comment]
@Shadow243 Please update as per https://github.com/cypht-org/cypht/wiki/Lifecycle

**Comment by kroky** [comment]
Hmm, maybe we need some more information on the merging strategy. I thought 2.x is always up to date with fixes and features that would be relased as part of 2.x branch - even 2.3.0. However, I see that might be a challenge backporting all that stuff constantly.
It might be easier to do the following:
- develop new features in master
- fix issues in master
- be sure to backport these fixes to 2.x branch - it is best at the time of merge or shortly after
- release 2.2.1, 2.2.2, etc. from 2.x branch (only fixes)
- release 2.3.0: merge the whole master into 2.x, release from 2.x and tag 2.3.0. Future fixes in 2.x will be released as 2.3.1, 2.3.2, etc. master continues with fixes and features which will later become 2.4.0 or even 3.0.0.

Once we hit a serious update worth bumping to 3.0.0, we can create a 3.x branch from master at that time and stop merging master into 2.x branch. Fixes can still be backported into 2.x branch. I think everything is covered this way.

**Comment by marclaporte** [comment]
@josaphatim @Shadow243 @Yannick243 @kambereBr @Baraka24 @IrAlfred 

Are you OK with this?

**Pull request merged**
